version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    ports: [ "6333:6333" ]
    volumes:
      - qdrantdata:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/collections"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ "9000:9000", "9001:9001" ]
    volumes:
      - miniodata:/data

  ollama:
    image: ollama/ollama:latest
    ports: [ "11434:11434" ]
    volumes:
      - ollamadata:/root/.ollama

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./infra/otel-collector.yaml:/etc/otel-collector.yaml
    ports: [ "4317:4317", "9464:9464" ]

  api-gateway:
    build: ./services/api-gateway
    env_file: ./services/api-gateway/.env.example
    environment:
      DATABASE_URL: postgres://rag:rag@postgres:5432/ragdb
      REDIS_URL: redis://redis:6379
      SPECIALIST_URL: http://ai-engine:8000
      OLLAMA_URL: http://ollama:11434
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on: [ postgres, qdrant, redis, ai-engine ]
    ports: [ "3000:3000" ]

  ai-engine:
    build: ./services/ai-engine
    env_file: ./services/ai-engine/.env.example
    environment:
      DATABASE_URL: postgres://rag:rag@postgres:5432/ragdb
      QDRANT_URL: http://qdrant:6333
      MINIO_ENDPOINT: http://minio:9000
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on: [ postgres, qdrant, redis ]
    ports: [ "8000:8000" ]

volumes:
  pgdata:
  qdrantdata:
  miniodata:
  ollamadata:
